### ISSUE TITLE
Fix build console warnings

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/threshold-management#69]
```

warning: 'error' is defined but never used (@typescript-eslint/no-unused-vars) at src/components/Image.vue:38:33:
  36 |           resolve(true);
  37 |         }
> 38 |         img.onerror = function (error) {
     |                                 ^
  39 |           reject(false);
  40 |         }
  41 |         img.src = src;


warning: Unexpected console statement (no-console) at src/components/Image.vue:54:13:
  52 |             this.imageUrl = this.src;
  53 |           }).catch(() => {
> 54 |             console.error("Image doesn't exist");
     |             ^
  55 |           })
  56 |         } else {
  57 |           // Image is from resource server, hence append to base resource url, check for existence and assign


warning: Unexpected console statement (no-console) at src/components/Image.vue:62:13:
  60 |             this.imageUrl = imageUrl;
  61 |           }).catch(() => {
> 62 |             console.error("Image doesn't exist");
     |             ^
  63 |           })
  64 |         }
  65 |       }


warning: 'translate' is defined but never used (@typescript-eslint/no-unused-vars) at src/components/JobConfiguration.vue:98:10:
   96 | } from "ionicons/icons";
   97 | import { mapGetters, useStore } from "vuex";
>  98 | import { translate } from "@/i18n";
      |          ^
   99 | import { DateTime } from 'luxon';
  100 | 
  101 | export default defineComponent({


warning: Unexpected console statement (no-console) at src/components/JobHistoryModal.vue:115:9:
  113 |         }
  114 |       } catch(err) {
> 115 |         console.error(err);
      |         ^
  116 |       }
  117 |     }
  118 |   },


warning: Unexpected console statement (no-console) at src/components/SaveThresholdModal.vue:134:9:
  132 |         }
  133 |       } catch (err) {
> 134 |         console.error(err)
      |         ^
  135 |         showToast(translate('Something went wrong'))
  136 |       }
  137 |       this.isServiceScheduling = false


warning: Unexpected console statement (no-console) at src/components/SaveThresholdModal.vue:214:9:
  212 |       } catch (err) {
  213 |         showToast(translate('Something went wrong'))
> 214 |         console.error(err)
      |         ^
  215 |       }
  216 |       return resp;
  217 |     }


warning: Unexpected console statement (no-console) at src/registerServiceWorker.ts:6:7:
  4 |   register(`${process.env.BASE_URL}service-worker.js`, {
  5 |     ready () {
> 6 |       console.log(
    |       ^
  7 |         'App is being served from cache by a service worker.\n' +
  8 |         'For more details, visit https://goo.gl/AFskqB'
  9 |       )


warning: Unexpected console statement (no-console) at src/registerServiceWorker.ts:12:7:
  10 |     },
  11 |     registered () {
> 12 |       console.log('Service worker has been registered.')
     |       ^
  13 |     },
  14 |     cached () {
  15 |       console.log('Content has been cached for offline use.')


warning: Unexpected console statement (no-console) at src/registerServiceWorker.ts:15:7:
  13 |     },
  14 |     cached () {
> 15 |       console.log('Content has been cached for offline use.')
     |       ^
  16 |     },
  17 |     updatefound () {
  18 |       console.log('New content is downloading.')


warning: Unexpected console statement (no-console) at src/registerServiceWorker.ts:18:7:
  16 |     },
  17 |     updatefound () {
> 18 |       console.log('New content is downloading.')
     |       ^
  19 |     },
  20 |     updated () {
  21 |       console.log('New content is available; please refresh.')


warning: Unexpected console statement (no-console) at src/registerServiceWorker.ts:21:7:
  19 |     },
  20 |     updated () {
> 21 |       console.log('New content is available; please refresh.')
     |       ^
  22 |     },
  23 |     offline () {
  24 |       console.log('No internet connection found. App is running in offline mode.')


warning: Unexpected console statement (no-console) at src/registerServiceWorker.ts:24:7:
  22 |     },
  23 |     offline () {
> 24 |       console.log('No internet connection found. App is running in offline mode.')
     |       ^
  25 |     },
  26 |     error (error) {
  27 |       console.error('Error during service worker registration:', error)


warning: Unexpected console statement (no-console) at src/registerServiceWorker.ts:27:7:
  25 |     },
  26 |     error (error) {
> 27 |       console.error('Error during service worker registration:', error)
     |       ^
  28 |     }
  29 |   })
  30 | }


warning: 'cachedEnum' is assigned a value but never used (@typescript-eslint/no-unused-vars) at src/store/modules/job/actions.ts:21:11:
  19 |     });
  20 |     if(enumIds.length <= 0) return enumIds.map((id: any) => state.enumIds[id]);
> 21 |     const cachedEnum = payload.map((id: any) => state.enumIds[id]);
     |           ^
  22 |     const resp = await JobService.fetchJobDescription({
  23 |       "inputFields": {
  24 |         "enumId": enumIds,


warning: Unexpected console statement (no-console) at src/store/modules/job/actions.ts:88:7:
  86 |     }).catch((err) => {
  87 |       commit(types.JOB_HISTORY_UPDATED, { jobs: [], total: 0 });
> 88 |       console.error(err);
     |       ^
  89 |       showToast(translate("Something went wrong"));
  90 |     }) 
  91 |   },


warning: Unexpected console statement (no-console) at src/store/modules/job/actions.ts:144:7:
  142 |     }).catch((err) => {
  143 |       commit(types.JOB_RUNNING_UPDATED, { jobs: [], total: 0 });
> 144 |       console.error(err);
      |       ^
  145 |       showToast(translate("Something went wrong"));
  146 |     }) 
  147 |   },


warning: Unexpected console statement (no-console) at src/store/modules/job/actions.ts:193:7:
  191 |     }).catch((err) => {
  192 |       commit(types.JOB_PENDING_UPDATED, { jobs: [], total: 0 });
> 193 |       console.error(err);
      |       ^
  194 |       showToast(translate("Something went wrong"));
  195 |     })
  196 |   },


warning: 'cachedTempExpr' is assigned a value but never used (@typescript-eslint/no-unused-vars) at src/store/modules/job/actions.ts:206:11:
  204 |     });
  205 |     if(tempIds.length <= 0) return tempExprIds.map((id: any) => state.temporalExp[id]);
> 206 |     const cachedTempExpr = tempExprIds.map((id: any) => state.temporalExp[id]);
      |           ^
  207 |     const resp = await JobService.fetchTemporalExpression({
  208 |         "inputFields": {
  209 |         "tempExprId": tempIds,


warning: Unexpected console statement (no-console) at src/store/modules/job/actions.ts:296:7:
  294 |     } catch (err) {
  295 |       showToast(translate('Something went wrong'))
> 296 |       console.error(err)
      |       ^
  297 |     }
  298 |     return resp;
  299 |   },


warning: Unexpected console statement (no-console) at src/store/modules/job/actions.ts:342:7:
  340 |     } catch (err) {
  341 |       showToast(translate('Something went wrong'))
> 342 |       console.error(err)
      |       ^
  343 |     }
  344 |     return resp;
  345 |   },


warning: Unexpected console statement (no-console) at src/store/modules/job/actions.ts:411:7:
  409 |     } catch (err) {
  410 |       showToast(translate('Something went wrong'))
> 411 |       console.error(err)
      |       ^
  412 |     }
  413 |     return resp;
  414 |   },


warning: Unexpected console statement (no-console) at src/store/modules/product/actions.ts:48:7:
  46 |       }
  47 |     } catch (error) {
> 48 |       console.error(error);
     |       ^
  49 |       showToast(translate("Something went wrong"));
  50 |     }
  51 |     return resp;


warning: Unexpected console statement (no-console) at src/store/modules/user/actions.ts:26:11:
  24 |         } else if (hasError(resp)) {
  25 |           showToast(translate('Sorry, your username or password is incorrect. Please try again.'));
> 26 |           console.error("error", resp.data._ERROR_MESSAGE_);
     |           ^
  27 |           return Promise.reject(new Error(resp.data._ERROR_MESSAGE_));
  28 |         }
  29 |       } else {


warning: Unexpected console statement (no-console) at src/store/modules/user/actions.ts:31:9:
  29 |       } else {
  30 |         showToast(translate('Something went wrong'));
> 31 |         console.error("error", resp.data._ERROR_MESSAGE_);
     |         ^
  32 |         return Promise.reject(new Error(resp.data._ERROR_MESSAGE_));
  33 |       }
  34 |     } catch (err) {


warning: Unexpected console statement (no-console) at src/store/modules/user/actions.ts:36:7:
  34 |     } catch (err) {
  35 |       showToast(translate('Something went wrong'));
> 36 |       console.error("error", err);
     |       ^
  37 |       return Promise.reject(new Error(err))
  38 |     }
  39 |     // return resp


warning: 'state' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/user/actions.ts:102:25:
  100 | 
  101 |   // Set User Instance Url
> 102 |   setUserInstanceUrl ({ state, commit }, payload){
      |                         ^
  103 |     commit(types.USER_INSTANCE_URL_UPDATED, payload)
  104 |   },
  105 | 


warning: 'commit' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/user/actions.ts:106:25:
  104 |   },
  105 | 
> 106 |   async getEComStores({ commit }, payload) {
      |                         ^
  107 |     let resp;
  108 | 
  109 |     try{


warning: Unexpected console statement (no-console) at src/store/modules/user/actions.ts:117:7:
  115 |       }
  116 |     } catch(err) {
> 117 |       console.error(err)
      |       ^
  118 |     }
  119 |   },
  120 | 


warning: 'dispatch' is defined but never used (@typescript-eslint/no-unused-vars) at src/store/modules/user/actions.ts:121:32:
  119 |   },
  120 | 
> 121 |   async setEComStore({ commit, dispatch }, payload) {
      |                                ^
  122 |     commit(types.USER_CURRENT_ECOM_STORE_UPDATED, payload.store);
  123 |   }
  124 | }


warning: Unexpected console statement (no-console) at src/store/modules/util/actions.ts:28:7:
  26 |       }
  27 |     } catch(err) {
> 28 |       console.error(err)
     |       ^
  29 |     }
  30 |   },
  31 | 


warning: Unexpected console statement (no-console) at src/store/modules/util/actions.ts:71:7:
  69 |       }
  70 |     } catch (err) {
> 71 |       console.error(err)
     |       ^
  72 |     }
  73 |     return {};
  74 |   },


warning: 'IonBackButton' is defined but never used (@typescript-eslint/no-unused-vars) at src/views/Settings.vue:39:10:
  37 | 
  38 | <script lang="ts">
> 39 | import { IonBackButton, IonButton, IonContent, IonHeader,IonIcon, IonItem, IonLabel, IonMenuButton, IonPage, IonSelect, IonSelectOption, IonTitle, IonToolbar, popoverController } from '@ionic/vue';
     |          ^
  40 | import { defineComponent } from 'vue';
  41 | import { codeWorkingOutline, ellipsisVertical, globeOutline, personCircleOutline, storefrontOutline} from 'ionicons/icons'
  42 | import { mapGetters, useStore } from 'vuex';


warning: 'popoverController' is defined but never used (@typescript-eslint/no-unused-vars) at src/views/Settings.vue:39:160:
  37 | 
  38 | <script lang="ts">
> 39 | import { IonBackButton, IonButton, IonContent, IonHeader,IonIcon, IonItem, IonLabel, IonMenuButton, IonPage, IonSelect, IonSelectOption, IonTitle, IonToolbar, popoverController } from '@ionic/vue';
     |                                                                                                                                                                ^
  40 | import { defineComponent } from 'vue';
  41 | import { codeWorkingOutline, ellipsisVertical, globeOutline, personCircleOutline, storefrontOutline} from 'ionicons/icons'
  42 | import { mapGetters, useStore } from 'vuex';


warning: 'emitter' is defined but never used (@typescript-eslint/no-unused-vars) at src/views/ThresholdUpdates.vue:242:8:
  240 | import JobConfiguration from '@/components/JobConfiguration.vue'
  241 | import { codeWorkingOutline, copyOutline, refreshOutline, timeOutline, timerOutline } from "ionicons/icons";
> 242 | import emitter from '@/event-bus';
      |        ^
  243 | import { Plugins } from '@capacitor/core';
  244 | import { showToast } from '@/utils'
  245 | import JobHistoryModal from '@/components/JobHistoryModal.vue';


35 warnings found.
```

**Comment by AmanPandagre21** [comment]
please assign this issue to me

**Comment by ymaheshwari1** [comment]
@AmanPandagre21 go ahead
